blog/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :menus

  get "jobs" => "jobs#index"
  root "jobs#index"

  get "mains" => "mains#index"
  # root "articles#index"

  # get "/articles", to: "articles#index"
  # get "/articles/:id", to: "articles#show"

  resources :articles do
    resources :comments
  end

  # get "/restaurants", to: "restaurants#restaurants"

  resources :restaurants do
    resources :menus do
    end
    delete "/menus/destroys" => "menus#destroys"
    # resources :staff
  end

  delete "/menus/destroys" => "menus#destroys"


  # resources :restaurants do
  #   resources :staff
  # end

  # https://tadhao.medium.com/member-vs-collection-in-rails-routes-ade10c8c5d19
  post "/restaurants/Test"
  post "/dinner/Test"
  post "/lunch2/Test"

end

blog/app/models/article.rb
class Article < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

  def foo
    "Hi, this is #{self.title}"
  end
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
  # 세션(서버 저장) , 쿠키, 헤더
  # devise Gem
  #

  def index
    puts Article.all
    @articles = Article.all
    puts "===== article Type ::: #{@articles.class}"
  end

  def show
    @article = Article.find(params[:id])

    puts @article.comments
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy

    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path, status: :see_other
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :status)
  end


end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <br>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'] %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

blog/app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

blog/app/views/articles/index.html.erb
<h1>Articles</h1>

Our blog has <%= Article.public_count %> articles and counting!

<ul>
  <% @articles %>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <li>
        <%= link_to article.title, article %>
      </li>
    <% end %>
  <% end %>
</ul>

<p><%= root_path %></p>
<p><%= articles_path %></p>
<p><%= new_article_path %></p>
<p><%= edit_article_path(2) %></p>

<%= link_to "New Article", new_article_path %>

blog/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

blog/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %></li>
</ul>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>