blog/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :menus

  get "jobs" => "jobs#index"
  root "jobs#index"

  get "mains" => "mains#index"
  # root "articles#index"

  # get "/articles", to: "articles#index"
  # get "/articles/:id", to: "articles#show"

  resources :articles do
    resources :comments
  end

  # get "/restaurants", to: "restaurants#restaurants"

  resources :restaurants do
    resources :menus do
    end
    delete "/menus/destroys" => "menus#destroys"
    # resources :staff
  end

  delete "/menus/destroys" => "menus#destroys"


  # resources :restaurants do
  #   resources :staff
  # end

  # https://tadhao.medium.com/member-vs-collection-in-rails-routes-ade10c8c5d19
  post "/restaurants/Test"
  post "/dinner/Test"
  post "/lunch2/Test"

end

blog/app/models/user.rb
class User < ApplicationRecord
end

blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    puts "===users create==="


    @user = User.new()
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]

    user_password_confirmation = params[:user][:password_confirmation]

    if @user.password != user_password_confirmation
      @errors = "password 일치하지 않음."

      puts @errors
      return @errors
    end

    puts "password Check #{user_password_confirmation}"

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:email])
    end

    # Only allow a list of trusted parameters through.
    # def user_params
    #   # params.fetch(:email, {})
    #   params.require(:user).permit(:email, :password)
    #   params.require(:params).permit(:password_confirmation)
    # end
end

blog/app/helpers/users_helper.rb
module UsersHelper
end

blog/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

blog/app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

blog/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

blog/app/views/users/index.html.erb
<div id="signUpStep1Con" style="display: block">
  <div id="contents">
    <%= button_tag "Restaurant", :type => 'button', :class => "subBtn", :onclick => "location.href = '#{restaurants_path}'" %>
  </div>


  <div>
    <div id="contents_wrap">
      <div id="contents">
        <form class="login_user" id="login_user" novalidate="">
          <div id="signInSignInCon" class="sign_con signin_con">
            <div class="sign_notice_info"><p>잡플래닛은 회원님의 익명성을 보장하기 위해<br> 어떠한 개인정보도 노출하지 않습니다.</p></div>
            <div class="signInsignIn_wrap">
              <div class="sign_wrap"><h2>로그인</h2>
                <section class="section_email er_r">

                  <fieldset>
                    <label class="email">
                      <span class="tit"></span>
                      <input data-valid="false" id="user_email" name="user[email]" placeholder="이메일 주소" type="email" value="">
                      <span class="error_txt">잘못된 형식의 이메일 주소입니다.</span>
                    </label>
                    <label class="password">
                      <span class="tit"></span>
                      <input data-valid="false" id="user_password" name="user[password]" placeholder="비밀번호 (8자리 이상)" type="password" value="">
                      <span class="error_txt">올바르지 않은 비밀번호 형식입니다.</span>
                    </label>
                    <%= button_tag "이메일로 로그인", :type => 'button', :class => "btn_sign_up", :onclick => "location.href = '#{restaurants_path}'" %>
                    <%= button_tag "Restaurant", :type => 'button', :class => "btn_sign_up signup_step1", :onclick => "location.href = '#{restaurants_path}'" %>
                  </fieldset>
                </section>

              </div>
              <section class="section_login">
                <p class="login_check">아직 회원이 아니세요?
                  <a>회원가입</a>
                </p>

              </section>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>




<div id="signUpStep2Con" style="display: none">>
  <div>
    <div id="contents_wrap">
      <div id="contents">
          <div id="signInSignInCon" class="sign_con signin_con">
            <div class="sign_notice_info"><p>잡플래닛은 회원님의 익명성을 보장하기 위해<br> 어떠한 개인정보도 노출하지 않습니다.</p></div>
            <div class="signInsignIn_wrap">
              <div class="sign_wrap"><h2>로그인</h2>
                <section class="section_email er_r">

                  <fieldset>
                    <label class="email">
                      <span class="tit"></span>
                      <input data-valid="false" id="user_email" name="user[email]" placeholder="이메일 주소" type="email" value="">
                      <span class="error_txt">잘못된 형식의 이메일 주소입니다.</span>
                    </label>
                    <label class="password">
                      <span class="tit"></span>
                      <input data-valid="false" id="user_password" name="user[password]" placeholder="비밀번호 (8자리 이상)" type="password" value="">
                      <span class="error_txt">올바르지 않은 비밀번호 형식입니다.</span>
                    </label>
                    <label class="password_check">
                      <span class="tit"></span>
                      <input data-valid="false" id="user_password_confirmation" name="user[password_confirmation]" placeholder="비밀번호 확인" type="password" value="">
                      <span class="error_txt">올바르지 않은 비밀번호 형식입니다.</span>
                    </label>
                    <button class="btn_sign_up" id="sign_up">회원가입</button>
                  </fieldset>

                </section>


              </div>
              <section class="section_login">
                <p class="login_check">이미 회원이세요?
                  <a>로그인</a>
                </p>
              </section>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>


<script>

  document.getElementsByClassName("login_check")[0].addEventListener('click', change_page1, false);
  document.getElementsByClassName("login_check")[1].addEventListener('click', change_page2, false);

  function change_page1(){
      console.log("1111")
      document.getElementById("signUpStep1Con").style.display = "none";
      document.getElementById("signUpStep2Con").style.display = "block";
  }
  function change_page2(){
      console.log("2222")
      document.getElementById("signUpStep1Con").style.display = "block";
      document.getElementById("signUpStep2Con").style.display = "none";
  }

  document.getElementById("sign_up").addEventListener('click', create_users, false);
  function create_users(){
      console.log("create Users");
      url = "/users"
  }
</script>

blog/app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

blog/app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>