blog/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :menus

  get "jobs" => "jobs#index"
  root "jobs#index"

  get "mains" => "mains#index"
  # root "articles#index"

  # get "/articles", to: "articles#index"
  # get "/articles/:id", to: "articles#show"

  resources :articles do
    resources :comments
  end

  # get "/restaurants", to: "restaurants#restaurants"

  resources :restaurants do
    resources :menus do
    end
    delete "/menus/destroys" => "menus#destroys"
    # resources :staff
  end

  delete "/menus/destroys" => "menus#destroys"


  # resources :restaurants do
  #   resources :staff
  # end

  # https://tadhao.medium.com/member-vs-collection-in-rails-routes-ade10c8c5d19
  post "/restaurants/Test"
  post "/dinner/Test"
  post "/lunch2/Test"

end

blog/app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :menus, dependent: :destroy
end

blog/app/controllers/restaurant_controller.rb
class RestaurantController < ApplicationController

  @@a = 1 # class variable
  @b  = 2 # class instance variable
  def index
    @Hello = "Hello?"
    puts @Hello
    puts "Get Index"

    ## Type Test
    @member = {
      "name" => "MSG",
      "age" => 29,
    }
    @typeTest = Hash.new()
    @typeTest['name'] = "KSG"
    puts "@member Type ::: #{@member.class}"
    puts "@TypeTest Type ::: #{@typeTest.class}"

    @restaurant = Restaurant.all
  end

  def create
    puts "POST Create"
    @c = 3 # instance variable

    puts @@a # => 1
    puts @b  # => nil, there is no instance variable @b
    puts @c  # => 3 # we defined this instance variable in the initializer
  end

  def lunch
    @c = 3 # instance variable

    puts @@a # => 1
    puts @b  # => nil, there is no instance variable @b
    puts @c  # => 3 # we defined this instance variable in the initializer
  end

  def Test
    # Get - Page 필수
    #
    puts "Test Def"
    puts @@a # => 1
    puts @b  # => nil, there is no instance variable @b
    puts @c  # => 3 # we defined this instance variable in the initialize
  end


  # 스케폴딩


  def new
    puts "new Start"
    @restaurant = Restaurant.new
    @lunch = Restaurant.new
    puts @lunch.class
    puts "restaurant name ::: #{@lunch.name} "
  end

  def create
    puts "Create Start"
    puts params
    @restaurant = Restaurant.new()
    @restaurant.name = params[:name]
    @restaurant.location = params[:location]
    @restaurant.genre = params[:genre]

    if @restaurant.save
      redirect_to '/restaurant'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    puts "Edit Start"
    puts params[:id]
    @restaurant = Restaurant.find(params[:id])
    puts @restaurant.id
    puts @restaurant.name

  end

  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update(restaurant_params)
      redirect_to '/restaurant'
    else
      render :edit, status: :unprocessable_entity
    end
  end


  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :location, :genre)
  end


end

blog/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  @@a = 1 # class variable
  @b  = 2 # class instance variable
  def index
    @Hello = "Hello?"
    puts @Hello
    puts "Get Index"

    ## Type Test
    @member = {
      "name" => "MSG",
      "age" => 29,
    }

    @typeTest = Hash.new()
    @typeTest['name'] = "KSG"
    puts "@member Type ::: #{@member.class}"
    puts "@TypeTest Type ::: #{@typeTest.class}"

    @restaurant = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])

  end

  def create
    puts "POST Create"
    @c = 3 # instance variable

    puts @@a # => 1
    puts @b  # => nil, there is no instance variable @b
    puts @c  # => 3 # we defined this instance variable in the initializer
  end

  def lunch
    HooService.test
    @c = 3 # instance variable

    puts @@a # => 1
    puts @b  # => nil, there is no instance variable @b
    puts @c  # => 3 # we defined this instance variable in the initializer
  end

  def Test
    # Get - Page 필수
    # self..
    puts "Test Def"
    puts @@a # => 1
    puts @b  # => nil, there is no instance variable @b
    puts @c  # => 3 # we defined this instance variable in the initialize

  end


  # 스케폴딩


  def new
    puts "new Start"
    @restaurant = Restaurant.new
    @lunch = Restaurant.new
    puts @lunch.class
    puts "restaurants name ::: #{@lunch.name} "
  end

  def create
    puts "Create Start"
    puts params
    @restaurant = Restaurant.new()
    @restaurant.name = params[:name]
    @restaurant.location = params[:location]
    @restaurant.genre = params[:genre]

    if @restaurant.save
      redirect_to '/restaurants'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    puts "Edit Start"
    puts params[:id]
    @restaurant = Restaurant.find(params[:id])
    @r =  {data: 1234}
    puts @restaurant.id
    puts @restaurant.name

    # ERB Sample Data Setting
    # @restaurant = Restaurant.new
    # @restaurant.name = "잡플 식당"
    # @restaurant.location = "선릉"

    # Json , Hash Data Setting
    @h = {
      id: 1,
      name: "msg",
      data: [
      ]
    }
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to '/restaurants'
  end



  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update(restaurant_params)
      redirect_to '/restaurants'
    else
      render :edit, status: :unprocessable_entity
    end
  end


  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :location, :genre)
  end


end

blog/app/helpers/restaurants_helper.rb
module RestaurantsHelper

end

blog/app/views/restaurants/edit.html.erb
<h1>Restaurant Edit</h1>
<div id="new">
  <%= form_with model: @restaurant do |form| %>
    <%= form.label :name, "Restaurant Name" %>
    <%= form.text_field :name%>

    <br>
    <%= form.label :location, "location" %>
    <%= form.text_field :location %>

    <br>
    <%= form.label :genre, "genre" %>
    <%= form.select :genre, ['한식', '중식', '일식'] %>
    <%= form.submit "식당 업데이트" %>
  <% end %>

  <%= @h[:id] %>
  <%= @h[:name] %>
  <%= @h[:data] %>

  <div id="msg">
    <% 5.times.each do |i| %>
      <span>Hello <%= i %></span>
    <% end %>
  </div>
</div>
<script>
  var a = "<%= "aaa" %>"
</script>

blog/app/views/restaurants/index.html.erb
<h1> lunch Index </h1>
<!--
<ul>
  <li><%#= link_to "restaurants" %></li>
</ul>
-->

<table>
  <thead>
  <th>name</th>
  <th>location</th>
  <th>recommend_menu</th>
  <th>recommend_cnt</th>
  <th>genre</th>
  </thead>
  <tbody>

  <% @restaurant.each do |restaurant| %>
    <tr>
      <td><%= link_to restaurant.name, "/restaurants/#{restaurant.id}" %></td>
      <td><%= restaurant.location %></td>
      <td><%= restaurant.recommend_menu %></td>
      <td><%= restaurant.recommend_cnt %></td>
      <td><%= restaurant.genre %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= button_to "식당 추가", new_restaurant_path, :method => "get" %>
<%= button_to "로그인", users_path, :method => "get" %>

<%= form_with url: "/restaurants/Test" do |form| %>
  <div>
    <%= form.submit "Post /restaurants/Test" %>
  </div>
<% end %>

<script>
</script>
<style>
    h1 {
        font-size : 35px;
        text-align : center;
    }

    table {
        font-family: Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    table td, #customers th {
        border: 1px solid #ddd;
        padding: 8px;
    }

    table tr:nth-child(even){background-color: #f2f2f2;}

    table tr:hover {background-color: #ddd;}

    table th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: center;
        background-color: #04AA6D;
        color: white;
    }

    button {
        background-color: #4CAF50; /* Green */
        border: none;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
    }
</style>

blog/app/views/restaurants/lunch.html.erb
<div>
  <p>Json/Hash</p>
  <p>Name : <%= @member['name'] %></p>
  <p>Age : <%= @member['age'] %></p>
</div>

<div>
  <p><%= root_path %></p>
  <p><%= articles_path %></p>
  <p><%= new_article_path %></p>
  <p><%= edit_article_path(2) %></p>
</div>

<h1><%= @index %></h1>
<h1><%= @Hello %></h1>
<h1><%= @open %></h1>
<ul>
  <li><%= link_to "test",  "/restaurants/Test"%></li>
</ul>

<!--
  cmd Test
  link_to - get 호출
  link_to "표시값", path
-->
<%= form_with url: "/restaurants/Test" do |form| %>
  <div>
    <%= form.submit %>
  </div>
<% end %>

<h1> 연습 </h1>

<script>
</script>
<style>
    h1 {
        font-size : 35px;
        text-align : center;
    }

</style>

blog/app/views/restaurants/new.html.erb
<h1>Restaurant Create</h1>

<div id="new">
  <%= form_with url: "/restaurants" do |form| %>
    <%= form.label :name, "Restaurant Name" %>
    <%= form.text_field :name %>

    <br>
    <%= form.label :location, "location" %>
    <%= form.text_field :location %>

    <br>
    <%= form.label :genre, "genre" %>
    <%= form.select :genre, ['한식', '중식', '일식'] %>
    <%= form.submit "생성" %>
  <% end %>

  <%= form_with url: "/restaurants", method: :get do |form| %>
    <div>
      <%= form.submit "되돌아가기 Get "%>
    </div>
  <% end %>
</div>

blog/app/views/restaurants/show.html.erb
<h1> 식당 정보 </h1>
<div id="new">
<%= form_with model: @restaurant do |form| %>
  <%= form.label :name, "Restaurant Name" %>
  <%= form.text_field :name, readonly: true%>

  <br>
  <%= form.label :location, "location" %>
  <%= form.text_field :location , readonly: true%>

  <br>
  <%= form.label :genre, "genre" %>
  <%= form.select :genre, ['한식', '중식', '일식'], {}, disabled: true%>
<% end %>
<%= button_to "수정", edit_restaurant_path(@restaurant), :method => "get" %>
<%= button_to "삭제", restaurant_path(@restaurant), :method => "delete" %>


<%= button_to "돌아가기 Ruby", restaurants_path, :method => "get" %>
<button id="restaurant">돌아가기 JS 처리</button>

<h1> 메뉴 정보 값 변경</h1>

<table id="menus">
  <thead>
    <th>수정</th>
    <th>name</th>
    <th>price</th>
    <th>taste</th>
    <th>volume</th>
    <th>recommend_cnt</th>
    <th>삭제</th>
  </thead>
  <tbody>


  <% @restaurant.menus.each do |menu| %>
    <tr>
      <td> <input type="checkbox" name="menu_check" data-value="<%= menu.id %>"/> </td>
      <td><%= link_to menu.name, edit_restaurant_menu_path(@restaurant.id, menu.id) %></td>
      <td><%= menu.price %>원</td>
      <td><%= menu.taste %>점</td>
      <td><%= menu.volume %>점</td>
      <td><%= menu.recommend_cnt %></td>
      <td>
        <%= link_to "삭제", restaurant_menu_path(@restaurant.id, menu.id), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      } %>


    </tr>
  <% end %>
  </tbody>
</table>

<%= button_to "추가", new_restaurant_menu_path(@restaurant), method: "get" %>
<%= button_to "삭제", restaurant_menu_path(@restaurant.id, 0),
              form: { id: "delete_menus"},
              method: :delete,
              data: {turbo_confirm: "Are you sure?"}%>

<button id="btn_del">삭제 by button</button>



<h1> 메뉴 정보 (Form 포함) </h1>
<table id="menus2">
  <thead>
  <th>수정</th>
  <th>name</th>
  <th>price</th>
  <th>taste</th>
  <th>volume</th>
  <th>recommend_cnt</th>
  <th>삭제</th>
  </thead>
  <tbody>


  <% @restaurant.menus.each do |menu| %>
    <tr>
      <td> <input type="checkbox" name="menus[status]" /> </td>
      <td><%= link_to menu.name, edit_restaurant_menu_path(@restaurant.id, menu.id) %></td>
      <td><%= menu.price %>원</td>
      <td><%= menu.taste %>점</td>
      <td><%= menu.volume %>점</td>
      <td><%= menu.recommend_cnt %></td>
      <td>
        <%= link_to "삭제", restaurant_menu_path(@restaurant.id, menu.id), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        } %>


    </tr>
  <% end %>
  </tbody>
</table>


</div>
<script>
    menus = document.getElementsByName('menu_check');
    for (i=0; i<menus.length; i++){
        menus[i].addEventListener('change', console_add, false);
    }
    function console_add(e){
        if (e.currentTarget.checked) {
            let action_value =  document.getElementById("delete_menus").action
            action_value = action_value + e.currentTarget.dataset.value + ","
            document.getElementById("delete_menus").action = action_value
        } else {

        }
    }

    document.getElementById("restaurant").addEventListener('click', function(){
        location.href = `${"<%= restaurants_path %>"}`
      /*  location.replace(`${"<%= restaurants_path %>"}`) */
    }, false);


</script>

<style>
    .button_to {
        width: 20%;
        display: inline-block;
    }
    h1 {
        font-size : 35px;
        text-align : center;
    }

    table {
        font-family: Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    table td, #customers th {
        border: 1px solid #ddd;
        padding: 8px;
    }

    table tr:nth-child(even){background-color: #f2f2f2;}

    table tr:hover {background-color: #ddd;}

    table th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: center;
        background-color: #04AA6D;
        color: white;
    }


</style>